### ISSUE TITLE
How to write `use` correctly?

### ISSUE THREAD

**Issue by blindFS** [nushell/tree-sitter-nu#165]
Confused by this usage: `use std assert equal`,
I mean why not `use std [assert equal]` or `use std "assert equal"`? 

Maybe it's module inside module?

**Comment by NotTheDr01ds** [comment]
> Maybe it's module inside module?

That's correct. In that form, it means:

1. Import the `std` module
1. Import the `assert` submodule definition from inside the `std` module
1. Import the `equal` definition from the `assert` submodule

It's generally not recommended any longer, since the following form is faster:

```nushell
use std/assert equal
```

That skips the first step above and *just* loads `assert` as a module using its path.

The less efficient form was common up until recently and is still found in a lot of older code, though.

**Comment by blindFS** [comment]
@NotTheDr01ds thanks for the explanation, it makes perfect sense. Glad to hear that it's not the recommended way, and I tend to not fix it in tree-sitte-nu 😆. The canonical ways are a lot easier to parse, and are already supported.
